### ISSUE TITLE
Citations don't display in citations tab

### ISSUE THREAD

**Issue by Dominic-DallOsto** [diegodlh/zotero-wikicite#64] opened 2021-04-09 14:59 UTC
I just followed the following process to add citations to an item in my library.
* Item already had a DOI (10.3389/fnins.2011.00149)
* Got QID for item (Q40797145)
* More... -> Sync citations with Wikidata

The citations appear to have been synced successfully as there is a note added to the entry (attached)
[citations.txt](https://github.com/diegodlh/zotero-wikicite/files/6286584/citations.txt)

But then, nothing is displayed in the citations tab for the entry. In the Zotero error console, the following error is displayed:

```
[JavaScript Error: "NS_ERROR_UNEXPECTED: " {file: "chrome://wikicite/content/main.js" line: 5131}]
updateCitations@chrome://wikicite/content/main.js:5131:21
SourceItemWrapper@chrome://wikicite/content/main.js:5037:5
@chrome://wikicite/content/main.js:2952:9
mountState@chrome://wikicite/content/main.js:31413:20
useState@chrome://wikicite/content/main.js:32035:16
useState@chrome://wikicite/content/main.js:44465:10
CitationsBoxContainer@chrome://wikicite/content/main.js:2950:40
renderWithHooks@chrome://wikicite/content/main.js:30772:18
mountIndeterminateComponent@chrome://wikicite/content/main.js:33598:13
beginWork@chrome://wikicite/content/main.js:34836:16
callCallback@chrome://wikicite/content/main.js:19732:9
invokeGuardedCallbackDev@chrome://wikicite/content/main.js:19781:7
invokeGuardedCallback@chrome://wikicite/content/main.js:19843:3
beginWork$1@chrome://wikicite/content/main.js:39746:7
performUnitOfWork@chrome://wikicite/content/main.js:38561:12
workLoopSync@chrome://wikicite/content/main.js:38489:5
renderRootSync@chrome://wikicite/content/main.js:38452:7
performSyncWorkOnRoot@chrome://wikicite/content/main.js:38075:18
./node_modules/react-dom/cjs/react-dom.development.js/flushSyncCallbackQueueImpl/<@chrome://wikicite/content/main.js:27114:26
unstable_runWithPriority@chrome://wikicite/content/main.js:46397:12
runWithPriority$1@chrome://wikicite/content/main.js:27063:10
flushSyncCallbackQueueImpl@chrome://wikicite/content/main.js:27109:9
flushSyncCallbackQueue@chrome://wikicite/content/main.js:27096:3
scheduleUpdateOnFiber@chrome://wikicite/content/main.js:37675:9
updateContainer@chrome://wikicite/content/main.js:41264:3
legacyRenderSubtreeIntoContainer@chrome://wikicite/content/main.js:41819:5
render@chrome://wikicite/content/main.js:41885:10
refreshCitationsPane@chrome://wikicite/content/main.js:6936:11
refreshCitationsPane@chrome://wikicite/content/main.js:6542:3
onxblmousedown@chrome://global/content/bindings/tree.xml:1156:14
```

I am happy to provide any extra info / help debug. I saw in #41 that addons could possibly cause a related error, so I have the following addons installed if that helps: better bibtex, libreoffice integration, word for windows integration, zotfile, and zotxt

**Comment by DominicD-823543** [comment] 2021-04-09 15:32
After updating my better bibtex add on (5.2.23 to 5.2.144) I no longer experience this error and citations are displayed as expected.

To check, I reverted my profile and database, repeated the exact same steps as above (installed wikicite addon, got QID, synced citations) but the error doesn't occur. Sorry for the confusion

**Comment by diegodlh** [comment] 2021-04-09 18:25
Hi, Dominic! Thank you so much for taking the time to test the addon  #and to report this issue with so much detail. No need to be sorry at all!

I'll close this one and mark it as duplicate of #41. Thanks!

Duplicate of #41

**Closed by diegodlh** 2021-04-09 18:25 UTC

**Comment by diegodlh** [comment] 2021-04-09 18:26
Duplicate of #41
